### PR TITLE
Add feature "[data-export] Delete button"

### PR DESCRIPTION
**Pull request by ogomezba**
Hi! I've created this PR to implement the feature described in #134.

Test evidence after opening the test-framework page:
Screenshot 2023-10-08 a las 22 27 08

Thank you!

### CODE REVIEW

**Comment by tprouvot** [comment]
Thank you very much @ogomezba  ! 
This is great job 👍 

Could you use the "linkTarget" variable used in props to define if the link must open in a new tab or the current one ?
The goal is to let users decide it based on a [custom setting ](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/78)

image

**Comment by tprouvot** [comment]
Optional parts which can be done after (and if you want to) :

- add tests in data-export-test and data-import-test to cover this new functionality
- delete only filtered records from data export page ([WIP here](https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/142))

**Comment by ogomezba** [comment]
Thank you @tprouvot for the great suggestions! I was not sure about what was the best way to include the changes in the other branch for the filtered records to make them work with my changes. I've included what I needed directly in my changes. Should I have merged the branch into mine instead?

Also, if you have any suggestions for the tests, please feel free to comment.

**Comment by tprouvot** [comment]
Hi @ogomezba 
Thanks for the updates and sorry for the delay ⌛  ! 
I'll add those improvements in the CHANGES.md which is used to describe the release updates.

FYI when doing the tests on this feature, I created a [new one](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/193) pretty much linked to it, which goal is to .... undelete records 😄

Good job on this PR 👏  happy to welcome you to the team !

**Pull request merged**
