### PR TITLE
Push events

### PR DESCRIPTION
**Pull request by dufoli**
## Checklist before requesting a review
- [ ] I have read and understand the [Contributions section](https://github.com/tprouvot/Salesforce-Inspector-reloaded#contributions)
- [ ] Target branch is releaseCandidate and not master
- [ ] I have performed a self-review of my code
- [ ] I ran the [unit tests](https://github.com/tprouvot/Salesforce-Inspector-reloaded#unit-tests) and my PR does not break any tests
- [ ] I documented the changes I've made on the [CHANGES.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/CHANGES.md) and followed actual conventions
- [ ] I added a new section on [how-to.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/docs/how-to.md) (optional)

### CODE REVIEW

**Comment by tprouvot** [comment]
I think that this PR is supposed to be made on your fork right ? @dufoli

**Comment by dufoli** [comment]
@tprouvot sorry it is because github set by default your project because I fork from this repo but I can not remove the default pull request destination ... I close th PR

**Comment by tprouvot** [comment]
To remove reloaded as default PR destination you could [detach the fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork)

**Comment by dufoli** [comment]
I know but the note said that we lost PR, issue.... That s why I do not do it. there is no way to remove without lost of metadata.

`The new repository will not retain any of its issues, pull requests, wikis, stars, watchers, comments, child forks, or other metadata that may currently be associated with your current fork.`

**Pull request closed without merging**
