### PR TITLE
Show field api name on record page

### PR DESCRIPTION
**Pull request by MD931**
Hi Thomas,
This pull request introduces a new feature that enhances the user experience when viewing record pages on Salesforce. It enables to display the Field API Name, providing valuable information for administrators and developers.
It works on Layouts & Dynamic Forms.

Capture d’écran 2023-11-05 à 23 34 45

Capture d’écran 2023-11-05 à 23 00 47

Merci 😁

### CODE REVIEW

**Comment by tprouvot** [comment]
Hi @MD931,
Thanks for this PR ! 

I've already seen this functionality on other extensions but never had the idea to implement it on sfir.
Could you describe a use case where this is more relevant than the show all data page ?

Except some particular use cases where you have multiples fields with same label, I can't really figure it out.
If we found use cases, I would include the button just after the show all data, to only display it on record page and not all pages

**Comment by MD931** [comment]
@tprouvot I can make an update to display the button after the "Show All Data" button on a record page.

**Comment by tprouvot** [comment]
> @tprouvot I can make an update to display the button after the "Show All Data" button on a record page.

That would be great !  
I was thinking that we may have too many buttons on the popup so I created a [new feature request](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/203) that would help to reduce the number of buttons displayed

**Comment by MD931** [comment]
Hi @tprouvot 
I've made the changes, and now the button is displayed exclusively on a Lightning record page. I also took the opportunity to show the API Name of the fields within a quick action of a related record.

Capture d’écran 2023-11-06 à 12 40 02

Thank you 🙂

**Comment by tprouvot** [comment]
Hi @MD931,
I added a new element of 'mark' type to highlight the api name.
During the test I've found a behaviour that may affect users when trying to copy the api name:
On double click (to select the api name) the UI triggers the edit mode which removes the api name

**Comment by MD931** [comment]
> Hi @MD931, I added a new element of 'mark' type to highlight the api name. During the test I've found a behaviour that may affect users when trying to copy the api name: On double click (to select the api name) the UI triggers the edit mode which removes the api name  [  ](https://user-images.githubusercontent.com/35368290/280727324-95a129b1-6fca-42e8-8e1f-7f534b055a34.gif) [ ](https://user-images.githubusercontent.com/35368290/280727324-95a129b1-6fca-42e8-8e1f-7f534b055a34.gif)

Yes, it's tricky, and unfortunately, it removes the API Name. I don't have a solution for that. What I could do is store the API Name to the clipboard with a single click on the API Name

**Comment by tprouvot** [comment]
> > Hi @MD931, I added a new element of 'mark' type to highlight the api name. During the test I've found a behaviour that may affect users when trying to copy the api name: On double click (to select the api name) the UI triggers the edit mode which removes the api name
> >       
> >         

> >             
> >               
> >             
> >       
> 
> Yes, it's tricky, and unfortunately, it removes the API Name. I don't have a solution for that. What I could do is store the API Name to the clipboard with a single click on the API Name

Copy the api name to the clipboard could be a good option but we need to give this information to the user.
I think that a cursor over the api name would prevent users to double click and I'm also thinking to use a copy icon as cursor.
Just wondering if the UI won't be too ugly 😄

**Comment by MD931** [comment]
> > > Hi @MD931, I added a new element of 'mark' type to highlight the api name. During the test I've found a behaviour that may affect users when trying to copy the api name: On double click (to select the api name) the UI triggers the edit mode which removes the api name
> 
> > > 
> > 
> > 
> > Yes, it's tricky, and unfortunately, it removes the API Name. I don't have a solution for that. What I could do is store the API Name to the clipboard with a single click on the API Name
> 
> Copy the api name to the clipboard could be a good option but we need to give this information to the user. I think that a cursor over the api name would prevent users to double click and I'm also thinking to use a copy icon as cursor. Just wondering if the UI won't be too ugly 😄
> 
>  

I have just made a new commit that incorporates the copy cursor and also enables copying the API Name with a single click.

**Comment by MD931** [comment]
Hi @tprouvot 

I have just made some changes. Now, the button is no longer visible when no field is found. 

Thanks 😁

**Comment by tprouvot** [comment]
@MD931 That's great ! thanks for this 👏 
Now I have just one use case missing: the console.
When enabled, the show all data is not available, could you check if you can find an element in the page which can be used with and without the console enabled ?

image

Keep going, you're close to the end !

**Comment by tprouvot** [comment]
> Hi @tprouvot
> 
> I just modified the code by adding the necessary selector for the console mode.
> 
> Thank you 😅

Hi @MD931 
Unfortunately I don't have the button with the console:

image

**Comment by MD931** [comment]
Hi @tprouvot 

Sorry. I don't know why some console apps have a selector 'div.content' and others don't. I just updated it by changing the selector to 'section.oneConsoleTab'

**Comment by tprouvot** [comment]
Hi @MD931 
No updates from my side 😢 :

image


image

**Comment by tprouvot** [comment]
image

**Comment by tprouvot** [comment]
fix #202

**Pull request merged**
