### PR TITLE
sosl support init

### LINKED ISSUE #131: [data-export] Include a SOSL editor
**Is your feature request related to a problem? Please describe.**

I still use https://workbench.developerforce.com/ to create SOSL query's as i have not found a better alternative out there. Would be great to have this in the same plugin as Salesforce Inspector. 

**Describe the solution you'd like**
In the "Data-export" window i would like a button/switch/tab to go to a SOSL editor. 
In the SOSL editor i would like to be able to create SOSL queries as text input. 

**Describe alternatives you've considered**
- Extended SOSL version would be to give end users a UI to create the SOSL req similar to https://workbench.developerforce.com/. 

image

### PR DESCRIPTION
**Pull request by dufoli**
fix #131 DRAFT

### CODE REVIEW

**Comment by dufoli** [comment]
@tprouvot it seems to work. I need feedback on UX and from general point of view. Anyway it is working well.

**Comment by dufoli** [comment]
I have improved a little bit intellisens and remove need of checkbox, I detect if search mode if we start with select or find...
better approach because less ux impact and totaly transparent for users.

**Comment by dufoli** [comment]
I have added unit test but I can not test it because process for unit test is unclear and seems to now worked on import. whereas  I touch only export.
BTW, I have remove the .sf/ which is the new folder for sf client.

**Comment by dufoli** [comment]
@tprouvot any news for review ?

**Comment by tprouvot** [comment]
Hi @dufoli,

Thanks for the PR ! 

I need to take some time to perform a deep review of this PR since there's some consequent changes.
I'll keep you informed in this thread 👀

**Comment by dufoli** [comment]
hello, I will update the current branch.
I will do my own fork because the current projet need big refactoring I want to have : 
support apex runner for batch and queue and keep history of command (avoid anonymous console and keep in a file the commande to run)
 log analyzer to troubleshoot org limit .(today analysing why we rich org limits with logs is a really a pain in the ass).
 migrate to typescript (low priority)
 unit test in buildbot (high priority)
 refactor parser with tokenizer/lexer for query in date-export and move it out of component
 move intelisens over text area with list as regular IDE do instead of bottom.
 update react version and migrate code (high priority for security reason at least)
use dependatbot or mend renovate git bot to keep react and all dependency up to date.
 sosl support in data export
 export guess for object and externalid
...

**Comment by dufoli** [comment]
let s close this PR because, you have no time to review and I do not want to waste time to rebas for nothing. It s already on my fork anyway. Good luck and have fun.

**Pull request closed without merging**
