### PR TITLE
fix: double 'show all data' button in case of multiple objects with the same id prefix

### PR DESCRIPTION
**Pull request by baslu93**
This issue was happening because ContentDocument and ContentNote have the same Id Prefix.
I'm now passing the RowObjectType to renderCell, so that the ObjecType is given and it doesn't need to be calculated via the prefix.

Unit test evidence:
image

### CODE REVIEW

**Comment by tprouvot** [comment]
Great thank you very much @baslu93 for this **quick** fix ! 
I'll try test this today, kudos for the run of the tests, you're the first one to do it 👏

**Comment by tprouvot** [comment]
Hi @baslu93,
I can see a regression for polymorphic fields when trying to showAll data :

**Comment by baslu93** [comment]
Hi @tprouvot,

Interesting, I think the condition I adjusted is doing more than what I was expecting.
Thank you for testing, and apologize for that.

I'm reviewing it.

**Comment by baslu93** [comment]
Hi @tprouvot,

I changed the approach here.

**objectType** is something you can't be get from the SalesforceId prefix in some cases (e.g. in ContentDocument, CaseComments, ...)
So when "Show all data" page is loading (when isTooling=false), I use the ui-api to get the **objectType**.
If isTooling=true remained ASIS.

I prefered to work on "Show all data" because there's only one record there, and 1 api call is needed, in the data extract page more api calls were needed.

I'm using the `/ui-api/records/${recordId}?layoutTypes=Compact` which seems to be the lightest, since I need it to get **objectType** only.

Let me know you feeling.

**Pull request closed without merging**
