### PR TITLE
Handle LocaleSidKeys with multiple underscores + (Latin)

### PR DESCRIPTION
**Pull request by baslu93**
The current method isn't handling multiple underscores in LocalSidKey.
There are multiple values with 2 underscores:

- de_DE_EURO
- uz_LATN_UZ
- zh_CN_PINYIN
- zh_CN_STROKE
- zh_HK_STROKE
- zh_TW_STROKE

uz_LATN_UZ has been handled with an ad-hoc rule since LATN means Latin and the country is UZ.
One of the impact is the following flag, that is not showing correctly for the value de_DE_EURO (e.g.):

image

### CODE REVIEW

**Comment by tprouvot** [comment]
Hi @baslu93 thanks for your PR ! 
Could you :

- change the target branch to releaseCandidate ? 
- reference this fix in CHANGES.md file by following current convention ? 

Thanks a lot !

**Comment by baslu93** [comment]
Hey @tprouvot!

In CHANGES.md, I'll create a new bullet point (first in the list) in version 1.18 - General, with the following text:
- Fix country codes from LocalSidKey convention https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/117 (contribution by [Luca Bassani](https://github.com/baslu93))

Is it good?

**Comment by tprouvot** [comment]
> Hey @tprouvot!
> 
> In CHANGES.md, I'll create a new bullet point (first in the list) in version 1.18 - General, with the following text:
> 
> * Fix country codes from LocalSidKey convention [PR117](https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/117) (contribution by [Luca Bassani](https://github.com/baslu93))
> 
> Is it good?

Check on releaseCandidate branch, there is already a new version 1.19 but for the text it's perfect 👏

**Comment by tprouvot** [comment]
Thanks for your contribution @baslu93 ! 🙏 
If you are interested in more collaboration you can take a look at the the issues with "help wanted" label or even submit new feature requests !
Have a good day 🌞

**Pull request merged**
