### PR TITLE
Fix popup not closing in inspect page

### PR DESCRIPTION
**Pull request by baslu93**
## Describe your changes

Fix popup not closing in inspect page when:
 - Clicking outside the popup

**Side note:** I skipped the test on AccountContantRelationship, rest all good (for my POV we can move from AccountContactRelationship to another entity which is available by default, e.g.: AccountEventChange)

## Issue ticket number and link
[issue 159](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/159)

## Checklist before requesting a review
- [x] I have read and understand the [Contributions section](https://github.com/tprouvot/Salesforce-Inspector-reloaded#contributions)
- [x] Target branch is releaseCandidate and not master
- [x] I have performed a self-review of my code
- [x] I ran the [unit tests](https://github.com/tprouvot/Salesforce-Inspector-reloaded#unit-tests) and my PR does not break any tests
- [x] I documented the changes I've made on the [CHANGES.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/CHANGES.md) and followed actual conventions
- [ ] I added a new section on [how-to.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/docs/how-to.md) (optional)

### CODE REVIEW

**Comment by baslu93** [comment]
**New scope (TBD):**
1. RowTable (React) - Table settings
   image
2. FieldValueCell (React) - Record link
   image
3. FieldActionsCell (React) - Dropdown
   image
4. ChildActionsCell (React) - Relationship dropdown
   image

**Comment by tprouvot** [comment]
Hi @baslu93 

Would you like me to merge this one or add the new scope in the same PR?

**Comment by baslu93** [comment]
Hi @tprouvot,

I implemented the additional changes in the same PR 🤞

**Comment by baslu93** [comment]
**New approach:**

When a popup is open, it registers the popup component in `popupTmpReactElement`. It's "tmp" to avoid issues when multiple popup creator components are clicked.

When something is clicked, it checks if there's a popup component registered. If so, it checks if the click is not inside the popup and closes it.

**Side note:** Middle click is not implemented, but the same behavior is present in data-export.html. When you click "Show all data", the popup doesn't close; I'm fine with it.

**Comment by tprouvot** [comment]
Thank you @baslu93 🚀

**Pull request merged**
