### PR TITLE
Automatically request SObject type when data export from an SObject r…

### PR DESCRIPTION
**Pull request by dufoli**
…ecord (#45)

### CODE REVIEW

**Comment by dufoli** [comment]
DRAFT

**Comment by tprouvot** [comment]
Hi @dufoli 
Thanks for the PR, I always wanted to adress this but didn't had the time to do so.

I can see a regression for the functionnality which detects the SObject on list view pages.
First load was from releaseCandidate branch, where we can see that Contact object is detected, second load is with your branch where the object is not detected.


The second point is, when searching from the object tab and selecting a value, I would like to use this object for export query

Cf the following example, I'm on contact list view page when I click on export the selected object id Contact which is fine.
But if I'm selecting AccounCleanInfo, I'm expecting to have this object in export page.
What do you think about this ?

**Comment by dufoli** [comment]
Can you gave me the url format of list you use because I am on lightning maybe it is classic url format?
I will handle second point first.

**Comment by dufoli** [comment]
both point is fixed

**Comment by dufoli** [comment]
rebase and need new review.

**Comment by dufoli** [comment]
@tprouvot any news for review ?

**Comment by tprouvot** [comment]
Hi @dufoli,
Thanks for the PR ! 
Since this feature could modify existing behaviour I think we should let users decide if they want to enable / disable this functionality.
There's an [incoming PR](https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/244) which will display settings in a dedicated page.
For now we can just use a localStorage variable "useSObjectContextOnDataImportLink"
ie `localStorage.getItem("useSObjectContextOnDataImportLink")`
Question is : should we enable it by default or disable ?

**Comment by dufoli** [comment]
hello, yes it change behaviour but is it an issue?
People can get with first item of query history the last query so in just one click you get last query.
I prefer convention over configuration. 
Imo, if tool is well design, we do not need a lot of configuration but you have access to all features you need.
If you really want option, I will add it but really but not sure.

**Comment by tprouvot** [comment]
> hello, yes it change behaviour but is it an issue? People can get with first item of query history the last query so in just one click you get last query. I prefer convention over configuration. Imo, if tool is well design, we do not need a lot of configuration but you have access to all features you need. If you really want option, I will add it but really but not sure.

Ok let's do this, we can add the parameter later if requested by community.
Thanks for the PR 👍

**Comment by tprouvot** [comment]
#341

**Pull request merged**
