### PR TITLE
feat[data-export]:add format query button to allow users to format SOQL queries

### PR DESCRIPTION
**Pull request by dyncan**
## Describe your changes
Add a "Format Query" button to the [Data Export] section, allowing users to format their SOQL query for an enhanced view of the query's structure

__Note:__ Currently the "Format Query" button does not support *Comment* and *SOSL*.

## Issue ticket number and link
N/A
## Checklist before requesting a review
- [x] I have read and understand the [Contributions section](https://github.com/tprouvot/Salesforce-Inspector-reloaded#contributions)
- [x] Target branch is releaseCandidate and not master
- [x] I have performed a self-review of my code
- [x] I ran the [unit tests](https://github.com/tprouvot/Salesforce-Inspector-reloaded#unit-tests) and my PR does not break any tests
- [x] I documented the changes I've made on the [CHANGES.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/CHANGES.md) and followed actual conventions
- [ ] I added a new section on [how-to.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/docs/how-to.md) (optional)

### CODE REVIEW

**Comment by tprouvot** [comment]
Hi @dyncan 
Thanks for this PR ! 

I think that the 'Format Query' button may be useful for users but I'm a little bit annoyed by adding a 287 KB file for this since minified react only weights 124 KB.

I would prefer a much lighter solution to handle the formating of SOQL

**Comment by dyncan** [comment]
Hi @tprouvot 
Thanks for the feedback.

I understand your concern, I'll look into alternatives and update accordingly.

**Comment by tprouvot** [comment]
Hi @dyncan,
Have you considered other options for formatting ?

**Comment by dyncan** [comment]
@tprouvot  Currently, no better alternative has been found. I believe this library effectively resolves the issue of SOQL formatting. I also attempted to repackage and optimize the library’s source code using webpack, yet the size of the package still exceeds 200KB.

**Comment by tprouvot** [comment]
Hi @dyncan,
I'm not aware of the framework but I think our need is much more lighter than what soql-parser.js can do.
Have you considered creating a function which parses the query for the basics needs of formatting ?

**Comment by dyncan** [comment]
@tprouvot  I have been also considering whether it is possible to update a mini version in the SOQL format. However, due to work commitments, I haven't had the time. I plan to submit a beta version soon, and then we can discuss it together.

**Comment by dyncan** [comment]
Hi @tprouvot 
Formatting SOQL requires considering various scenarios, such as subqueries and nested subqueries, and complex where conditions, etc. which makes it somewhat complex. Currently, I have only implemented formatting for standard SOQL (without subqueries ), and supporting more complex SOQL might be challenging.

**Comment by tprouvot** [comment]
Hi @dyncan 
I'm closing this PR since the addition of a soql parser framework has been rejected for now.
Please let me know if you want to implement a new custom beautifier.
FYI the new version will support SOSL and GraphQL language in addition of SOQL

**Comment by dyncan** [comment]
Hi @tprouvot 

Thank you for the update. I understand the decision and appreciate the information on the upcoming features.

I also look forward to contributing more meaningful PRs in the future.

**Pull request closed without merging**
